

//  ---------- INLCUDED BLOCK: BranchComparatorW  ---------- 
//  ---------- INCLUDED BLOCK: BranchComparator ---------- 
module BranchComparatorW (
    input  [31:0] i_rs1,
    input  [31:0] i_rs2,
    input  [2:0]  i_funct3, // The 3-bit control signal from the instruction
    output reg    o_Branch_Taken
);
    // RISC-V Branch funct3 codes mapped to localparams
    localparam c_BR_BEQ  = 3'b000;
    localparam c_BR_BNE  = 3'b001;
    localparam c_BR_BLT  = 3'b100;
    localparam c_BR_BGE  = 3'b101;
    localparam c_BR_BLTU = 3'b110;
    localparam c_BR_BGEU = 3'b111;

    always @(*) begin
        case(i_funct3)
            c_BR_BEQ:  o_Branch_Taken = (i_rs1 == i_rs2) ? 1'b1 : 1'b0;
            c_BR_BNE:  o_Branch_Taken = (i_rs1 != i_rs2) ? 1'b1 : 1'b0;
            
            // Signed comparisons require casting with $signed()
            c_BR_BLT:  o_Branch_Taken = ($signed(i_rs1) < $signed(i_rs2)) ? 1'b1 : 1'b0;
            c_BR_BGE:  o_Branch_Taken = ($signed(i_rs1) >= $signed(i_rs2)) ? 1'b1 : 1'b0;
            
            // Unsigned comparisons
            c_BR_BLTU: o_Branch_Taken = (i_rs1 < i_rs2) ? 1'b1 : 1'b0;
            c_BR_BGEU: o_Branch_Taken = (i_rs1 >= i_rs2) ? 1'b1 : 1'b0;
            
            default:   o_Branch_Taken = 1'b0; // Default to not taken to prevent latches
        endcase
    end
endmodule


// Automatically generated by ChipInventor Cloud EDA Tool - 3.15
// Careful: this file (hdl.v) will be automatically replaced
// when you ask tool to generate top Verilog code by clicking
// at BLOCKS button.

module top (

  input wire [31:0] i_rs1,
  input wire [31:0] i_rs2,
  input wire [2:0] i_funct3,
  output wire o_Branch_Taken

);
//Instances of Modules
BranchComparatorW blk2848_1 (
         .i_rs1 (i_rs1 [31:0]),
         .i_rs2 (i_rs2 [31:0]),
         .i_funct3 (i_funct3 [2:0]),
         .o_Branch_Taken (o_Branch_Taken)
     );


endmodule
